import { NgModule } from '@angular/core';
import {
    MatAutocompleteModule,
    MatButtonModule,
    MatButtonToggleModule,
    MatCardModule,
    MatCheckboxModule,
    MatChipsModule,
    MatDatepickerModule,
    MatDialogModule,
    MatExpansionModule,
    MatFormFieldModule,
    MatGridListModule,
    MatIconModule,
    MatInputModule,
    MatListModule,
    MatMenuModule,
    MatNativeDateModule,
    MatProgressBarModule,
    MatProgressSpinnerModule,
    MatRadioModule,
    MatSelectModule,
    MatSnackBarModule,
    MatTabsModule,
    MatTooltipModule,
    MatSliderModule,
    MatSlideToggleModule,
    MatStepperModule,
    MatSidenavModule,
    MatDividerModule,
    MatToolbarModule,
    MatBadgeModule
} from '@angular/material';

import { MatCarouselModule } from '@ngmodule/material-carousel';
import { FlexLayoutModule } from '@angular/flex-layout';
import { NgxMatSelectSearchModule } from 'ngx-mat-select-search';
import { MatMomentDateModule } from '@angular/material-moment-adapter';

@NgModule({
    imports: [
        MatButtonModule,
        MatCheckboxModule,
        MatFormFieldModule,
        MatInputModule,
        MatProgressSpinnerModule,
        MatSnackBarModule,
        MatTooltipModule,
        MatTabsModule,
        MatDialogModule,
        MatChipsModule,
        MatSelectModule,
        MatProgressBarModule,
        MatMenuModule,
        MatButtonToggleModule,
        MatCardModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatGridListModule,
        MatExpansionModule,
        MatAutocompleteModule,
        MatRadioModule,
        MatListModule,
        MatIconModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatExpansionModule,
        MatCarouselModule,
        MatStepperModule,
        MatSidenavModule,
        MatDividerModule,
        MatToolbarModule,
        FlexLayoutModule,
        MatBadgeModule,
        NgxMatSelectSearchModule,
        MatMomentDateModule
    ],
    exports: [
        MatButtonModule,
        MatCheckboxModule,
        MatFormFieldModule,
        MatInputModule,
        MatProgressSpinnerModule,
        MatSnackBarModule,
        MatTooltipModule,
        MatTabsModule,
        MatDialogModule,
        MatChipsModule,
        MatSelectModule,
        MatProgressBarModule,
        MatMenuModule,
        MatButtonToggleModule,
        MatCardModule,
        MatDatepickerModule,
        MatNativeDateModule,
        MatGridListModule,
        MatExpansionModule,
        MatAutocompleteModule,
        MatRadioModule,
        MatListModule,
        MatIconModule,
        MatSliderModule,
        MatSlideToggleModule,
        MatExpansionModule,
        MatCarouselModule,
        MatStepperModule,
        MatSidenavModule,
        MatDividerModule,
        MatToolbarModule,
        FlexLayoutModule,
        MatBadgeModule,
        NgxMatSelectSearchModule,
        MatMomentDateModule
    ]
})
export class JhMaterialModule {}
